#!/bin/bash

# up_brightness.sh and dim_brightness.sh scripts must be sudo-eable
# In sudoers file, something like:
#   bruno Loulou=NOPASSWD: /home/bruno/.i3-blocks/scripts/up_brightness.sh, /home/bruno/.i3-blocks/scripts/dim_brightness.sh

# One of the following: xrandr, xbacklight, kernel
METHOD="kernel"

SCRIPTS_DIR=`dirname $0`/../scripts/

case $BLOCK_BUTTON in
  # scroll up, increase
  4) sudo $SCRIPTS_DIR/up_brightness.sh ;;
  # scroll down, decrease
  5) sudo $SCRIPTS_DIR/dim_brightness.sh ;;
esac

URGENT_VALUE=10

if [[ "${METHOD}" = "xrandr" ]]; then
  device="${BLOCK_INSTANCE:-primary}"
  xrandrOutput=$(xrandr --verbose)

  if [[ "${device}" = "primary" ]]; then
    device=$(echo "${xrandrOutput}" | grep 'primary' | head -n 1 | awk -F ' ' '{print $1}')
  fi

  curBrightness=$(echo "${xrandrOutput}" | grep "${device}" -A 5 | grep -i "Brightness" | awk -F ':' '{print $2}')
elif [[ "${METHOD}" = "kernel" ]]; then
  device="${BLOCK_INSTANCE:-intel_backlight}"
  maxBrightness=$(cat /sys/class/backlight/${device}/max_brightness)
  curBrightness=$(cat /sys/class/backlight/${device}/brightness)
elif [[ "${METHOD}" = "xbacklight" ]]; then
  curBrightness=$(xbacklight -get)
fi

if [[ "${curBrightness}" -le 0 ]]; then
  exit
fi

if [[ "${METHOD}" = "xrandr" ]]; then
  percent=$(echo "scale=0;${curBrightness} * 100" | bc -l)
elif [[ "${METHOD}" = "kernel" ]]; then
  percent=$(echo "scale=3;${curBrightness} / ${maxBrightness} * 100" | bc -l | sed 's/[\.,][0-9]*//g')
elif [[ "${METHOD}" = "xbacklight" ]]; then
  percent=$(echo "scale=0;${curBrightness}" | bc -l)
fi

percent=${percent%.*}

echo "${percent}%"
echo "${percent}%"
echo ""

if [[ "${percent}" -le "${URGENT_VALUE}" ]]; then
  exit 33
fi
