#!/bin/bash
export HAMSTER_DB_FILE_PATH=~/snap/hamster-snap/47/.local/share/hamster/hamster.db
NAME=$(/home/bruno/dev/dotfiles/scripts/hamster-get_current_activity_name.py)
TIME=$(/home/bruno/dev/dotfiles/scripts/hamster-get_today_worked_time.py)

echo "$NAME 🕜︎ $TIME"

case $BLOCK_BUTTON in
1) /home/bruno/dev/gitlabtimesync/stop_current_activity.py;;
esac